# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-27 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='custom_id',
            new_name='barcode_id',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='qr_id',
            new_name='barcode_id',
        ),
    ]
