# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-27 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190227_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
